import 'package:flutter/material.dart';
import '../models/category.dart';
import '../models/product.dart';

class TextileConstants {
  static const List<TextileCategory> categories = [
    TextileCategory(
      id: 'cat_sarees',
      name: 'Sarees',
      icon: Icons.checkroom,
      imageUrl:
          'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=600',
      description:
          'Elegant Indian heritage silk, georgette, and designer sarees.',
    ),
    TextileCategory(
      id: 'cat_fabrics',
      name: 'Fabrics',
      icon: Icons.texture,
      imageUrl:
          'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=600',
      description:
          'Premium unstitched fabric rolls in linen, cotton, denim, and silks.',
    ),
    TextileCategory(
      id: 'cat_kurtis',
      name: 'Kurtis',
      icon: Icons.star_border,
      imageUrl:
          'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=600',
      description: 'Trendy daily wear and ethnic embroidered Kurtis for women.',
    ),
    TextileCategory(
      id: 'cat_bedsheets',
      name: 'Bedsheets',
      icon: Icons.bed,
      imageUrl:
          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=600',
      description:
          'Luxury high-thread-count cotton bedsheets and home furnishings.',
    ),
  ];

  static const List<Product> products = [
    // === Sarees ===
    Product(
      id: 'prod_saree_1',
      name: 'Royal Banarasi Silk Saree',
      description:
          'Exquisite handwoven Banarasi silk saree featuring intricate zari work and gold-embroidered borders. Ideal for weddings, festivals, and grand occasions. Comes with a matching unstitched silk blouse piece.',
      price: 4999.00,
      discountPrice: 4249.00,
      imageUrl:
          'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Sarees',
      fabricType: 'Banarasi Silk',
      pattern: 'Zari Weaving',
      width: '44 inches',
      gsm: 80,
      color: 'Crimson Red & Gold',
      minOrderQty: '1 Piece',
      rating: 4.8,
      reviewsCount: 34,
      isAvailable: true,
      stockQuantity: 15,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_saree_2',
      name: 'Classic Kanchipuram Silk Saree',
      description:
          'Traditional Kanchipuram silk saree with classic temple border motifs. Made from 100% pure mulberry silk and double-twisted threads for an unmatched drape and luxurious shine.',
      price: 7500.00,
      discountPrice: null,
      imageUrl:
          'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Sarees',
      fabricType: 'Kanchipuram Silk',
      pattern: 'Traditional Borders',
      width: '45 inches',
      gsm: 90,
      color: 'Emerald Green & Gold',
      minOrderQty: '1 Piece',
      rating: 4.9,
      reviewsCount: 18,
      isAvailable: true,
      stockQuantity: 8,
      stockStatus: 'Low Stock',
    ),
    Product(
      id: 'prod_saree_3',
      name: 'Bandhani Tie & Dye Silk Saree',
      description:
          'Authentic Rajasthani Bandhani saree hand-knotted and tie-dyed on premium art silk fabric. Adorned with gota patti border embellishments. Lightweight and colorful.',
      price: 3200.00,
      discountPrice: 2850.00,
      imageUrl:
          'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Sarees',
      fabricType: 'Art Silk',
      pattern: 'Bandhej Tie & Dye',
      width: '44 inches',
      gsm: 70,
      color: 'Marigold Yellow & Red',
      minOrderQty: '1 Piece',
      rating: 4.6,
      reviewsCount: 22,
      isAvailable: true,
      stockQuantity: 12,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_saree_4',
      name: 'Pastel Chanderi Cotton Silk Saree',
      description:
          'Elegant sheer pastel saree woven from high-quality Chanderi cotton-silk blends. Features traditional silver-threaded floral motifs (butis) and a glossy border. Exudes subtle luxury.',
      price: 4500.00,
      discountPrice: 3800.00,
      imageUrl:
          'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Sarees',
      fabricType: 'Chanderi Blend',
      pattern: 'Silver Zari Butis',
      width: '44 inches',
      gsm: 55,
      color: 'Mint Green / Silver',
      minOrderQty: '1 Piece',
      rating: 4.7,
      reviewsCount: 14,
      isAvailable: true,
      stockQuantity: 5,
      stockStatus: 'Low Stock',
    ),
    Product(
      id: 'prod_saree_5',
      name: 'Organza Floral Print Saree',
      description:
          'Modern, romantic designer saree made from light-as-air glass organza. Showcases large hand-painted style floral patterns and finished with neat satin piping. Easy to drape and very stylish.',
      price: 2400.00,
      discountPrice: null,
      imageUrl:
          'https://images.unsplash.com/photo-1608748010899-18f300247112?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1608748010899-18f300247112?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Sarees',
      fabricType: 'Glass Organza',
      pattern: 'Floral Painted',
      width: '44 inches',
      gsm: 45,
      color: 'Lilac & Blush Pink',
      minOrderQty: '1 Piece',
      rating: 4.4,
      reviewsCount: 29,
      isAvailable: true,
      stockQuantity: 20,
      stockStatus: 'In Stock',
    ),

    // === Fabrics ===
    Product(
      id: 'prod_fabric_1',
      name: 'Pure Organic Linen Fabric Roll',
      description:
          'Premium 100% organic linen fabric roll. Exceptionally breathable, moisture-wicking, and pre-washed for a soft feel. Excellent choice for creating summer shirts, trousers, dresses, and home decor linings.',
      price: 450.00,
      discountPrice: 399.00,
      imageUrl:
          'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1506806732259-39c2d0268443?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Fabrics',
      fabricType: '100% Linen',
      pattern: 'Plain / Solid Weave',
      width: '58 inches',
      gsm: 160,
      color: 'Natural Oatmeal',
      minOrderQty: '10 Meters',
      rating: 4.6,
      reviewsCount: 52,
      isAvailable: true,
      stockQuantity: 250,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_fabric_2',
      name: 'Premium Indigo Denim Fabric',
      description:
          'Heavyweight 12oz raw denim fabric colored with natural indigo dyes. Perfect for durable jeans, jackets, structured shirts, aprons, and bags. High quality and sturdy weave.',
      price: 350.00,
      discountPrice: null,
      imageUrl:
          'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Fabrics',
      fabricType: 'Cotton Denim',
      pattern: 'Twill Weave',
      width: '60 inches',
      gsm: 380,
      color: 'Deep Indigo Blue',
      minOrderQty: '15 Meters',
      rating: 4.5,
      reviewsCount: 29,
      isAvailable: true,
      stockQuantity: 180,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_fabric_3',
      name: 'Handspun Khadi Cotton Fabric',
      description:
          'Eco-friendly, hand-spun and hand-woven khadi cotton fabric. Cool in summer and warm in winter. Soft texture that gets better with every wash. Sourced directly from village cooperative weavers.',
      price: 220.00,
      discountPrice: 190.00,
      imageUrl:
          'https://images.unsplash.com/photo-1506806732259-39c2d0268443?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1506806732259-39c2d0268443?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Fabrics',
      fabricType: 'Khadi Cotton',
      pattern: 'Textured Solid',
      width: '44 inches',
      gsm: 120,
      color: 'Ivory White',
      minOrderQty: '20 Meters',
      rating: 4.7,
      reviewsCount: 41,
      isAvailable: true,
      stockQuantity: 400,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_fabric_4',
      name: 'French Heavyweight Linen Fabric',
      description:
          'Extra thick and structured French linen roll. Specially woven for upholstery, heavy curtains, outerwear, structured bags, and rustic tablecloths. Exceptionally durable.',
      price: 650.00,
      discountPrice: 590.00,
      imageUrl:
          'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Fabrics',
      fabricType: '100% Linen',
      pattern: 'Heavy Canvas Weave',
      width: '58 inches',
      gsm: 280,
      color: 'Charcoal Gray',
      minOrderQty: '8 Meters',
      rating: 4.8,
      reviewsCount: 19,
      isAvailable: true,
      stockQuantity: 90,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_fabric_5',
      name: 'Bamboo Cotton Jersey Knit',
      description:
          'Stretchy, buttery-soft jersey knit blended from eco-friendly bamboo fibers and combed cotton. Highly breathable and stretches well. Excellent for custom t-shirts, baby clothing, and lounge wear.',
      price: 290.00,
      discountPrice: null,
      imageUrl:
          'https://images.unsplash.com/photo-1506806732259-39c2d0268443?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1506806732259-39c2d0268443?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Fabrics',
      fabricType: 'Bamboo Blend',
      pattern: 'Solid Knit',
      width: '62 inches',
      gsm: 210,
      color: 'Sage Green',
      minOrderQty: '12 Meters',
      rating: 4.5,
      reviewsCount: 33,
      isAvailable: true,
      stockQuantity: 150,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_fabric_6',
      name: 'Pure Mulberry Silk Satin Roll',
      description:
          'Luxury unstitched mulberry silk fabric with a shiny, fluid drape satin finish. Ultimate premium choice for tailoring bridal gowns, high-end lining, shirts, and luxury silk pillowcases.',
      price: 1800.00,
      discountPrice: 1550.00,
      imageUrl:
          'https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Fabrics',
      fabricType: 'Mulberry Silk',
      pattern: 'Satin Solid',
      width: '44 inches',
      gsm: 75,
      color: 'Champagne Gold',
      minOrderQty: '5 Meters',
      rating: 4.9,
      reviewsCount: 25,
      isAvailable: true,
      stockQuantity: 40,
      stockStatus: 'Low Stock',
    ),

    // === Kurtis ===
    Product(
      id: 'prod_kurti_1',
      name: 'Anarkali Floral Georgette Kurti',
      description:
          'A beautiful flared Anarkali-style Kurti crafted in soft faux georgette fabric. Adorned with delicate floral prints, a sweetheart neck, and quarter sleeves. Includes a matching inner lining.',
      price: 1599.00,
      discountPrice: 1299.00,
      imageUrl:
          'https://images.unsplash.com/photo-1608748010899-18f300247112?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1608748010899-18f300247112?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Kurtis',
      fabricType: 'Georgette',
      pattern: 'Floral Printed',
      width: 'Stitched (M/L/XL)',
      gsm: 70,
      color: 'Rose Pink & Cream',
      minOrderQty: '1 Piece',
      rating: 4.4,
      reviewsCount: 65,
      isAvailable: true,
      stockQuantity: 45,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_kurti_2',
      name: 'Jaipuri Handblock Printed Kurti',
      description:
          'Straight-cut cotton kurti made using authentic wooden hand-block printing techniques from Jaipur. Designed with button detailing on the neckline and side slits. Extremely breathable and comfortable.',
      price: 1200.00,
      discountPrice: 999.00,
      imageUrl:
          'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Kurtis',
      fabricType: '100% Cotton',
      pattern: 'Handblock Print',
      width: 'Stitched (L/XL/XXL)',
      gsm: 110,
      color: 'Indigo Blue & White',
      minOrderQty: '2 Pieces',
      rating: 4.5,
      reviewsCount: 38,
      isAvailable: true,
      stockQuantity: 20,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_kurti_3',
      name: 'Lucknowi Chikankari Embroidered Kurti',
      description:
          'Fine hand-embroidered Lucknowi Chikankari straight Kurti on soft georgette fabric. Displays delicate floral thread work (bakhiya/fanda stitches). Comes with a matching slips liner.',
      price: 1890.00,
      discountPrice: 1650.00,
      imageUrl:
          'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Kurtis',
      fabricType: 'Georgette Poly',
      pattern: 'Hand Chikankari',
      width: 'Stitched (S/M/L/XL)',
      gsm: 80,
      color: 'Powder Blue & White',
      minOrderQty: '1 Piece',
      rating: 4.7,
      reviewsCount: 28,
      isAvailable: true,
      stockQuantity: 18,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_kurti_4',
      name: 'Chevron Cotton Angrakha Kurti',
      description:
          'Flared side-tie Angrakha style casual daily wear Kurti. Cut from 100% premium cotton fabric, decorated with matching tassels and chevron block designs. Ideal summer ethnic comfort.',
      price: 1150.00,
      discountPrice: null,
      imageUrl:
          'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Kurtis',
      fabricType: '100% Cotton',
      pattern: 'Chevron Zigzag',
      width: 'Stitched (M/L/XL)',
      gsm: 115,
      color: 'Rust Orange / Cream',
      minOrderQty: '2 Pieces',
      rating: 4.3,
      reviewsCount: 16,
      isAvailable: true,
      stockQuantity: 30,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_kurti_5',
      name: 'Royal Velvet Kurti & Pant Set',
      description:
          'Luxury winter Kurti set. Rich soft velvet straight Kurti detailed with golden zardozi hand embroidery on the neckline, paired with matching straight velvet trousers.',
      price: 2999.00,
      discountPrice: 2499.00,
      imageUrl:
          'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Kurtis',
      fabricType: 'Micro Velvet',
      pattern: 'Zardozi Embroidery',
      width: 'Stitched (M/L/XL)',
      gsm: 250,
      color: 'Deep Wine / Plum',
      minOrderQty: '1 Set',
      rating: 4.8,
      reviewsCount: 11,
      isAvailable: true,
      stockQuantity: 6,
      stockStatus: 'Low Stock',
    ),

    // === Bedsheets ===
    Product(
      id: 'prod_bed_1',
      name: 'Egyptian Cotton Luxury Bedsheet Set',
      description:
          'Experience 5-star hotel luxury at home with this 500 thread-count Egyptian cotton king-size bedsheet set. Includes one flat sheet and two matching standard-size pillowcases. Soft satin finish.',
      price: 2499.00,
      discountPrice: 1999.00,
      imageUrl:
          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800',
        'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Bedsheets',
      fabricType: 'Egyptian Cotton',
      pattern: 'Striped Sateen',
      width: '108 x 108 inches',
      gsm: 180,
      color: 'Snow White / Slate Gray',
      minOrderQty: '1 Set',
      rating: 4.7,
      reviewsCount: 74,
      isAvailable: true,
      stockQuantity: 30,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_bed_2',
      name: 'Textured Jacquard Throw Cushion Covers',
      description:
          'Pack of 3 premium woven jacquard throw cushion covers. High quality zip enclosures and heavy-duty back lining. Elegant geometric patterns that instantly elevate your living room decor.',
      price: 899.00,
      discountPrice: null,
      imageUrl:
          'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Bedsheets',
      fabricType: 'Jacquard Blend',
      pattern: 'Geometric Woven',
      width: '16 x 16 inches',
      gsm: 320,
      color: 'Mustard Gold & Slate',
      minOrderQty: '1 Pack',
      rating: 4.3,
      reviewsCount: 15,
      isAvailable: false,
      stockQuantity: 0,
      stockStatus: 'Out of Stock',
    ),
    Product(
      id: 'prod_bed_3',
      name: 'Handblock Printed Cotton Durrie Rug',
      description:
          'Flat-weave traditional flooring carpet crafted from heavy coarse cotton yarn. Displays rich botanical motifs hand-pressed with natural dyes. Adds an ethnic touch to living spaces.',
      price: 1950.00,
      discountPrice: 1650.00,
      imageUrl:
          'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Bedsheets',
      fabricType: '100% Coarse Cotton',
      pattern: 'Botanical Block Print',
      width: '4 x 6 feet',
      gsm: 850,
      color: 'Indigo & Off-White',
      minOrderQty: '1 Piece',
      rating: 4.6,
      reviewsCount: 20,
      isAvailable: true,
      stockQuantity: 25,
      stockStatus: 'In Stock',
    ),
    Product(
      id: 'prod_bed_4',
      name: 'Warm Cotton Flannel Plaid Blanket',
      description:
          'Double-sided brushed cotton flannel blanket. Cozy, heavy-weight, and breathable. Finished with neat hemmed edges, detailed with a classic rustic tartan checker pattern.',
      price: 2200.00,
      discountPrice: 1899.00,
      imageUrl:
          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800',
      images: [
        'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800',
      ],
      category: 'Bedsheets',
      fabricType: 'Brushed Flannel',
      pattern: 'Plaid Checks',
      width: '90 x 100 inches',
      gsm: 310,
      color: 'Forest Green & Mustard',
      minOrderQty: '1 Piece',
      rating: 4.7,
      reviewsCount: 31,
      isAvailable: true,
      stockQuantity: 40,
      stockStatus: 'In Stock',
    ),
  ];
}
